import React from "react";
import { Metadata } from "next";
import SignUpPage from "@/app/(components)/auth/SignUpPage";
export const metadata: Metadata = {
  title: "Signup page",
  description: "Generated by create next app",
};

const SignUp = () => {
  return <SignUpPage />;
};

export default SignUp;
