import React from "react";
import { Metadata } from "next";
import LoginPage from "@/app/(components)/auth/LoginPage";
export const metadata: Metadata = {
  title: "Login page",
  description: "Generated by create next app",
};

const Login = () => {
  return <LoginPage />;
};

export default Login;
