import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth page",
  description: "Generated by create next app",
};

const LayoutAuth = ({ children }: React.PropsWithChildren) => {
  return (
    <div className="px-5 pt-3">
      <div className="flex items-center justify-center ">{children}</div>
    </div>
  );
};

export default LayoutAuth;
